import { Inter } from "next/font/google";
import Link from 'next/link';

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="p-4 bg-stone-100">
          <div className="flex items-center gap-4">
            <p className="font-medium">Navigation</p>
            <Link href='/'>Page 1</Link>
            <Link href='/page-2'>Page 2</Link>
          </div>
        </nav>
        <div className="p-4">
          {children}
        </div>
      </body>
    </html>
  );
}
